# Generated by Django 3.2.7 on 2021-10-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, db_index=True, max_length=140, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(db_index=True, default='anonymous', max_length=14, verbose_name='name'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
