# Generated by Django 3.2.7 on 2021-10-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211018_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
